apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stockflow-production
namePrefix: prod-

resources:
  - ../../base
  - secrets.yaml

images:
  - name: ghcr.io/OWNER/stockflow-backend
    newTag: latest
  - name: ghcr.io/OWNER/stockflow-frontend
    newTag: latest

patches:
  - path: ingress-host.yaml
  - path: replicas.yaml

configMapGenerator:
  - name: stockflow-config
    behavior: merge
    literals:
      - CORS_ORIGIN=https://stockflow.example.com
